In [1]:
# import widget classes and instantiate Network instance
from clustergrammer_widget import *
net = Network(clustergrammer_widget)

In [1]:
import csv
import numpy as np
import pandas as pd

In [2]:
# reading in the csv file as a new pandas dataframe called roi_df
#use pd.read_csv("the path to the csv file on ur computer")
Multimeas = pd.read_csv("C:/Users/chris/Desktop/projects/optometry/jupyter/opt.csv")

In [8]:
roi_df = Multimeas
roi_df

,Unnamed: 0,ind cell,total index,TARPg3,Islet1,Pax6,DAPI,CD15,GLT-1,Cav3.1,...,SCGN,Kv2.2,DAPI.2,CAVIII,Rec,DAPI.3,Calb,PKC,Parv,DAPI.4
0,21_s1m1,21_s1m1_cell 0,cell 0,1049.972,1219.007,449.386,369.136,1240.079,981.801,958.693,...,535.371,2556.831,417.485,2203.484,13829.995,360.501,1027.346,918.365,578.774,392.588
1,NaN,21_s1m1_cell 1,cell 1,395.788,1588.703,401.111,988.403,1032.487,689.971,897.504,...,581.832,2347.903,1335.316,2049.701,3100.799,551.900,639.677,961.900,549.374,2217.022
2,NaN,21_s1m1_cell 2,cell 2,453.132,1118.557,389.423,2316.406,1024.207,721.093,1008.160,...,1593.214,2509.955,2136.745,2155.466,2365.397,578.747,651.101,750.467,368.244,3577.374
3,NaN,21_s1m1_cell 3,cell 3,565.603,1665.260,1170.452,4304.305,1162.536,831.560,1058.113,...,398.049,2432.743,3310.959,1805.437,1456.221,795.310,671.911,724.990,251.416,6386.156
4,NaN,21_s1m1_cell 4,cell 4,474.185,1715.672,1364.448,1284.858,1074.590,735.607,919.485,...,487.929,2517.504,1794.311,1777.483,1389.022,492.442,620.084,747.552,279.824,2357.532
5,NaN,21_s1m1_cell 5,cell 5,489.498,1895.483,526.208,3884.522,1131.230,836.739,1014.064,...,581.351,2445.114,2483.683,2254.428,3052.163,653.723,679.968,805.010,264.807,5140.438
6,NaN,21_s1m1_cell 6,cell 6,555.135,1069.362,420.988,2019.306,1087.467,721.672,876.248,...,721.016,2415.474,2016.282,2163.559,2509.543,568.636,678.397,962.450,542.144,3144.598
7,NaN,21_s1m1_cell 7,cell 7,412.604,2604.476,542.122,3174.623,1047.102,744.626,903.238,...,429.601,2334.345,2329.341,2232.583,3664.120,634.762,845.913,1080.113,530.172,4615.724
8,NaN,21_s1m1_cell 8,cell 8,674.315,1547.361,572.972,1768.599,1160.208,793.278,1037.414,...,452.269,2370.343,1646.042,2305.185,2980.294,584.965,798.611,1618.762,1375.329,2534.641
9,NaN,21_s1m1_cell 9,cell 9,503.689,2437.244,904.448,2906.748,1054.896,714.839,896.123,...,383.455,2342.032,2285.144,2127.150,2378.254,662.628,1215.031,1216.468,922.402,4417.063
10,NaN,21_s1m1_cell 10,cell 10,1070.986,1445.439,690.070,1373.367,1312.773,1145.038,1232.595,...,501.018,2510.409,1271.964,2415.625,6519.384,537.078,1073.613,1518.069,1095.990,1632.557
11,NaN,21_s1m1_cell 11,cell 11,455.525,2302.930,2254.279,3280.239,1088.712,739.788,942.314,...,366.946,2461.318,2852.631,1743.278,1357.719,788.239,643.616,642.672,254.190,4540.725
12,NaN,21_s1m1_cell 12,cell 12,1014.459,1239.797,433.522,312.125,1304.674,980.336,974.005,...,510.927,2588.468,373.567,2796.146,16657.811,346.400,1502.461,1223.870,918.563,355.565
13,NaN,21_s1m1_cell 13,cell 13,488.118,1751.175,412.724,1671.130,1052.931,743.152,945.998,...,433.690,2335.946,1680.072,1754.563,2699.086,525.176,812.876,853.437,485.218,2616.457
14,NaN,21_s1m1_cell 14,cell 14,632.461,2545.598,1781.568,5091.065,1154.271,834.190,1000.138,...,401.305,2417.630,2858.768,1984.977,1874.134,800.961,674.594,739.816,259.155,5181.804
15,NaN,21_s1m1_cell 15,cell 15,426.542,2807.967,677.442,2957.409,1051.836,735.408,959.597,...,447.530,2359.182,2207.716,2845.533,1832.874,721.905,667.530,982.118,255.851,4393.780
16,NaN,21_s1m1_cell 16,cell 16,497.528,1614.073,398.925,2202.488,1075.220,728.026,971.305,...,403.560,2332.310,1863.252,2133.589,2648.133,580.804,955.560,757.806,280.319,3005.878
17,NaN,21_s1m1_cell 17,cell 17,239.808,1096.670,391.506,1371.309,967.829,688.348,978.198,...,336.125,2315.345,1330.472,2725.561,2107.963,577.062,664.963,933.223,252.410,2691.458
18,NaN,21_s1m1_cell 18,cell 18,607.985,3157.130,1356.181,4482.815,1144.578,769.205,981.387,...,463.002,2407.536,2563.650,2551.018,1515.528,779.983,695.413,941.413,308.644,4664.363
19,NaN,21_s1m1_cell 19,cell 19,446.523,1451.485,394.653,2434.176,1036.327,690.363,908.314,...,348.975,2355.272,1813.151,2326.056,2269.463,580.332,859.486,861.728,262.154,3049.285
20,NaN,21_s1m1_cell 20,cell 20,557.758,3145.843,3641.093,2297.152,1096.178,713.240,993.782,...,392.598,2516.380,2243.523,1835.258,1241.802,745.598,648.118,617.568,266.218,3253.920
21,NaN,21_s1m1_cell 21,cell 21,923.070,1208.625,423.476,312.262,1303.352,1021.031,1015.638,...,521.600,2530.410,372.024,2619.708,13899.627,327.223,1370.391,1337.906,1084.258,361.218
22,NaN,21_s1m1_cell 22,cell 22,431.035,1710.247,412.818,2694.618,1067.246,712.682,966.549,...,352.790,2348.537,1938.725,2474.099,1957.847,650.783,650.785,815.364,256.359,3514.308
23,NaN,21_s1m1_cell 23,cell 23,612.197,2364.809,1918.977,3879.139,1171.104,775.834,947.102,...,586.119,2468.674,2494.719,2002.213,1364.039,719.848,681.900,846.912,540.029,3925.137
24,NaN,21_s1m1_cell 24,cell 24,489.860,2491.575,786.660,3600.945,1135.870,759.555,941.939,...,518.059,2396.839,2334.365,2743.138,1676.619,733.093,692.585,934.345,331.309,4264.530
25,NaN,21_s1m1_cell 25,cell 25,461.896,1721.506,400.184,2551.570,1086.322,771.211,1069.144,...,400.964,2348.127,1791.994,2261.890,2494.067,587.509,629.791,858.607,257.553,3022.650
26,NaN,21_s1m1_cell 26,cell 26,460.951,2662.546,2981.929,2226.330,1098.226,705.358,963.354,...,563.767,2528.946,2486.908,1708.645,1196.588,854.327,632.454,605.551,287.338,3497.954
27,NaN,21_s1m1_cell 27,cell 27,603.708,1391.091,558.979,2398.632,1220.163,1021.118,1116.839,...,416.844,2308.609,1931.074,2293.803,3172.774,643.476,666.133,1137.854,764.926,3086.896
28,NaN,21_s1m1_cell 28,cell 28,536.017,1663.531,420.169,2648.065,1136.866,843.322,1069.777,...,395.820,2343.205,1890.267,2053.819,2985.171,591.150,633.140,797.793,291.009,3178.609
29,NaN,21_s1m1_cell 29,cell 29,671.506,1585.933,671.252,2071.955,1185.785,1016.380,1028.672,...,431.117,2319.538,1663.878,2103.568,3653.700,587.883,792.849,1307.527,1260.094,2682.272
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10642,NaN,23_s2m5_cell 433,cell 10642,1201.339,4722.237,3184.206,6137.447,1402.518,1217.316,1089.166,...,459.279,2062.101,2621.276,2062.789,1710.454,3264.953,3304.934,7436.171,10176.603,2847.314
10643,NaN,23_s2m5_cell 434,cell 10643,1260.095,5912.302,8343.175,4792.235,1379.076,1207.867,1129.352,...,1061.756,2324.629,3012.206,2108.518,1600.168,3807.727,1563.530,1449.629,875.930,3514.203
10644,NaN,23_s2m5_cell 435,cell 10644,1217.185,2540.647,1357.126,6972.280,1390.750,1237.120,1095.214,...,4243.859,2731.185,3151.317,2342.365,1813.313,3722.622,1742.228,2067.963,1509.084,3592.601
10645,NaN,23_s2m5_cell 436,cell 10645,1083.193,2357.743,2399.365,6009.328,1400.202,1221.667,1044.532,...,1006.158,2167.511,3110.071,2171.284,1608.397,3543.472,1442.188,1228.995,654.367,3345.528
10646,NaN,23_s2m5_cell 437,cell 10646,1323.879,2923.155,667.883,5748.105,1376.806,1233.451,1126.975,...,1657.756,2322.535,2357.096,3361.950,1989.646,3334.407,3876.484,3185.356,1589.493,3225.010
10647,NaN,23_s2m5_cell 438,cell 10647,1646.771,2034.677,1666.071,4705.713,1465.760,1229.961,1022.846,...,744.049,2116.032,2792.557,2360.413,1554.518,3676.683,1475.621,1392.139,845.019,2854.212
10648,NaN,23_s2m5_cell 439,cell 10648,1481.107,2231.922,2087.268,3631.609,1458.531,1231.914,1057.589,...,571.661,2149.310,2704.325,2355.505,1660.125,3664.133,1534.135,1722.312,1143.401,2965.714
10649,NaN,23_s2m5_cell 440,cell 10649,1440.103,2607.849,881.101,6366.771,1401.418,1302.923,1422.272,...,366.303,2045.954,2695.861,2487.495,2055.077,4051.820,2315.127,2933.464,1369.375,3594.214
10650,NaN,23_s2m5_cell 441,cell 10650,1334.827,3529.910,2669.528,7072.077,1454.482,1311.059,1313.192,...,362.673,2134.149,4006.549,2620.184,1805.053,4787.081,1604.267,2634.393,685.302,4437.168
10651,NaN,23_s2m5_cell 442,cell 10651,1092.567,3134.998,574.529,5046.661,1368.676,1330.021,1132.722,...,409.701,1965.510,1895.831,3752.556,2951.624,2679.791,1454.186,4165.684,2089.533,2585.713
10652,NaN,23_s2m5_cell 443,cell 10652,1173.750,3844.592,3434.863,6550.646,1421.182,1249.417,1037.092,...,359.565,2112.134,3941.788,2696.532,1683.602,5009.043,1529.653,3160.161,1040.292,4394.798
10653,NaN,23_s2m5_cell 444,cell 10653,1109.007,5328.785,1503.246,6424.943,1402.650,1295.626,1018.774,...,377.771,2061.579,3313.175,4847.993,2876.596,3945.515,1501.519,4068.906,1802.539,3712.067
10654,NaN,23_s2m5_cell 445,cell 10654,1080.829,3575.774,3488.376,7345.494,1400.377,1233.451,1017.047,...,335.282,2114.504,3792.138,2457.819,1793.418,4882.805,1534.792,1952.348,940.648,4243.227
10655,NaN,23_s2m5_cell 446,cell 10655,1553.253,1564.450,574.220,381.066,1436.171,1238.645,1034.565,...,452.297,2060.801,262.916,2184.517,27425.596,344.248,1645.729,3775.422,4630.975,427.271
10656,NaN,23_s2m5_cell 447,cell 10656,1122.101,1487.616,613.699,325.896,1523.664,1242.226,990.265,...,510.384,1968.542,246.673,2253.012,1382.027,301.935,1269.580,2641.824,909.583,402.571
10657,NaN,23_s2m5_cell 448,cell 10657,1157.649,1532.372,717.120,320.292,1597.275,1243.318,1043.988,...,576.958,2085.845,244.718,2350.346,1423.873,309.148,1351.746,2738.607,1016.833,404.440
10658,NaN,23_s2m5_cell 449,cell 10658,898.765,2124.038,819.428,4274.258,1386.656,1241.887,1083.648,...,448.034,1988.421,2115.541,3098.526,1882.922,3356.868,1611.061,6164.033,3909.530,2940.685
10659,NaN,23_s2m5_cell 450,cell 10659,1374.692,1499.566,579.667,371.866,1370.884,1202.983,986.329,...,397.003,2018.677,268.855,2039.588,33174.578,360.855,1475.627,2089.057,1794.778,547.486
10660,NaN,23_s2m5_cell 451,cell 10660,1082.643,1492.770,678.976,317.685,1658.703,1260.396,1048.441,...,602.086,2233.485,250.973,2485.234,1471.086,313.633,1434.727,2431.143,1103.137,418.832
10661,NaN,23_s2m5_cell 452,cell 10661,1462.765,4109.420,1486.639,5034.137,1358.959,1221.978,1012.685,...,412.128,2028.677,2907.172,2060.730,1769.366,3934.725,1758.632,2305.417,1625.500,3713.452
10662,NaN,23_s2m5_cell 453,cell 10662,807.476,3099.326,3638.127,4457.253,1349.074,1196.167,1006.035,...,358.258,2062.041,3196.301,1887.198,1576.413,3961.844,1430.633,1421.537,783.334,3483.287
10663,NaN,23_s2m5_cell 454,cell 10663,988.037,1359.498,523.357,353.138,1288.703,1186.454,939.772,...,334.866,1937.399,354.196,1722.756,20641.334,556.772,1440.829,1741.546,1284.671,823.134
10664,NaN,23_s2m5_cell 455,cell 10664,776.304,2289.537,2078.663,2347.032,1364.893,1194.288,986.767,...,452.204,2046.932,1900.573,1913.638,1504.537,2963.010,1574.291,1888.032,1312.913,2589.851
10665,NaN,23_s2m5_cell 456,cell 10665,793.235,1287.015,535.832,344.674,1260.659,1178.958,929.225,...,321.321,1927.521,276.074,1555.953,15318.738,355.696,1331.104,1236.212,738.146,494.726
10666,NaN,23_s2m5_cell 457,cell 10666,1142.176,2256.070,1639.552,5368.930,1363.650,1282.809,988.130,...,324.968,1973.864,2373.184,2211.485,2025.508,3322.257,1879.032,3837.997,3356.274,3053.856
10667,NaN,23_s2m5_cell 458,cell 10667,1177.950,2689.598,2756.862,4436.351,1446.288,1257.858,1005.053,...,558.317,2119.314,2898.238,2041.018,1641.001,3374.491,1626.323,2782.315,2203.175,3222.936
10668,NaN,23_s2m5_cell 459,cell 10668,1084.212,1520.146,709.164,315.369,1539.201,1283.480,1005.844,...,532.345,2000.037,247.416,1902.658,1402.561,293.473,1317.444,2195.271,867.341,399.250
10669,NaN,23_s2m5_cell 460,cell 10669,1134.498,2531.540,1010.463,5662.223,1378.762,1303.295,1002.945,...,340.682,1985.417,2585.735,2869.685,3069.165,3611.495,1598.963,5116.087,3133.865,3071.363
10670,NaN,23_s2m5_cell 461,cell 10670,1069.561,3109.789,3357.271,5675.363,1252.552,1083.666,887.379,...,364.401,2137.312,4109.876,2672.130,1959.346,5253.586,1566.262,2438.544,743.254,4602.046
10671,NaN,23_s2m5_cell 462,cell 10671,1288.273,5983.552,1180.479,5656.707,1433.615,1283.000,1035.776,...,418.329,2121.946,2912.233,5477.224,10313.843,3981.734,2348.213,6155.098,3884.273,3153.609

In [9]:
#look at histogram of DAPI values, keep only DAPI values above 1000
#roi_df=roi_df[roi_df["DAPI"]>2000]
roi_df.hist(column="DAPI", bins=50)
roi_df.hist(column="Pax6", bins=50)
roi_df.hist(column="Parv", bins=50)

array([[<matplotlib.axes._subplots.AxesSubplot object at 0x000001F4EDD71F28>]],
      dtype=object)

In [10]:
roi_df['binaryPax'] = (roi_df.Pax6 > 1500)*1
roi_df['binaryParv'] = (roi_df.Parv > 800)*1
roi_df

,Unnamed: 0,ind cell,total index,TARPg3,Islet1,Pax6,DAPI,CD15,GLT-1,Cav3.1,...,DAPI.2,CAVIII,Rec,DAPI.3,Calb,PKC,Parv,DAPI.4,binaryPax,binaryParv
0,21_s1m1,21_s1m1_cell 0,cell 0,1049.972,1219.007,449.386,369.136,1240.079,981.801,958.693,...,417.485,2203.484,13829.995,360.501,1027.346,918.365,578.774,392.588,0,0
1,NaN,21_s1m1_cell 1,cell 1,395.788,1588.703,401.111,988.403,1032.487,689.971,897.504,...,1335.316,2049.701,3100.799,551.900,639.677,961.900,549.374,2217.022,0,0
2,NaN,21_s1m1_cell 2,cell 2,453.132,1118.557,389.423,2316.406,1024.207,721.093,1008.160,...,2136.745,2155.466,2365.397,578.747,651.101,750.467,368.244,3577.374,0,0
3,NaN,21_s1m1_cell 3,cell 3,565.603,1665.260,1170.452,4304.305,1162.536,831.560,1058.113,...,3310.959,1805.437,1456.221,795.310,671.911,724.990,251.416,6386.156,0,0
4,NaN,21_s1m1_cell 4,cell 4,474.185,1715.672,1364.448,1284.858,1074.590,735.607,919.485,...,1794.311,1777.483,1389.022,492.442,620.084,747.552,279.824,2357.532,0,0
5,NaN,21_s1m1_cell 5,cell 5,489.498,1895.483,526.208,3884.522,1131.230,836.739,1014.064,...,2483.683,2254.428,3052.163,653.723,679.968,805.010,264.807,5140.438,0,0
6,NaN,21_s1m1_cell 6,cell 6,555.135,1069.362,420.988,2019.306,1087.467,721.672,876.248,...,2016.282,2163.559,2509.543,568.636,678.397,962.450,542.144,3144.598,0,0
7,NaN,21_s1m1_cell 7,cell 7,412.604,2604.476,542.122,3174.623,1047.102,744.626,903.238,...,2329.341,2232.583,3664.120,634.762,845.913,1080.113,530.172,4615.724,0,0
8,NaN,21_s1m1_cell 8,cell 8,674.315,1547.361,572.972,1768.599,1160.208,793.278,1037.414,...,1646.042,2305.185,2980.294,584.965,798.611,1618.762,1375.329,2534.641,0,1
9,NaN,21_s1m1_cell 9,cell 9,503.689,2437.244,904.448,2906.748,1054.896,714.839,896.123,...,2285.144,2127.150,2378.254,662.628,1215.031,1216.468,922.402,4417.063,0,1
10,NaN,21_s1m1_cell 10,cell 10,1070.986,1445.439,690.070,1373.367,1312.773,1145.038,1232.595,...,1271.964,2415.625,6519.384,537.078,1073.613,1518.069,1095.990,1632.557,0,1
11,NaN,21_s1m1_cell 11,cell 11,455.525,2302.930,2254.279,3280.239,1088.712,739.788,942.314,...,2852.631,1743.278,1357.719,788.239,643.616,642.672,254.190,4540.725,1,0
12,NaN,21_s1m1_cell 12,cell 12,1014.459,1239.797,433.522,312.125,1304.674,980.336,974.005,...,373.567,2796.146,16657.811,346.400,1502.461,1223.870,918.563,355.565,0,1
13,NaN,21_s1m1_cell 13,cell 13,488.118,1751.175,412.724,1671.130,1052.931,743.152,945.998,...,1680.072,1754.563,2699.086,525.176,812.876,853.437,485.218,2616.457,0,0
14,NaN,21_s1m1_cell 14,cell 14,632.461,2545.598,1781.568,5091.065,1154.271,834.190,1000.138,...,2858.768,1984.977,1874.134,800.961,674.594,739.816,259.155,5181.804,1,0
15,NaN,21_s1m1_cell 15,cell 15,426.542,2807.967,677.442,2957.409,1051.836,735.408,959.597,...,2207.716,2845.533,1832.874,721.905,667.530,982.118,255.851,4393.780,0,0
16,NaN,21_s1m1_cell 16,cell 16,497.528,1614.073,398.925,2202.488,1075.220,728.026,971.305,...,1863.252,2133.589,2648.133,580.804,955.560,757.806,280.319,3005.878,0,0
17,NaN,21_s1m1_cell 17,cell 17,239.808,1096.670,391.506,1371.309,967.829,688.348,978.198,...,1330.472,2725.561,2107.963,577.062,664.963,933.223,252.410,2691.458,0,0
18,NaN,21_s1m1_cell 18,cell 18,607.985,3157.130,1356.181,4482.815,1144.578,769.205,981.387,...,2563.650,2551.018,1515.528,779.983,695.413,941.413,308.644,4664.363,0,0
19,NaN,21_s1m1_cell 19,cell 19,446.523,1451.485,394.653,2434.176,1036.327,690.363,908.314,...,1813.151,2326.056,2269.463,580.332,859.486,861.728,262.154,3049.285,0,0
20,NaN,21_s1m1_cell 20,cell 20,557.758,3145.843,3641.093,2297.152,1096.178,713.240,993.782,...,2243.523,1835.258,1241.802,745.598,648.118,617.568,266.218,3253.920,1,0
21,NaN,21_s1m1_cell 21,cell 21,923.070,1208.625,423.476,312.262,1303.352,1021.031,1015.638,...,372.024,2619.708,13899.627,327.223,1370.391,1337.906,1084.258,361.218,0,1
22,NaN,21_s1m1_cell 22,cell 22,431.035,1710.247,412.818,2694.618,1067.246,712.682,966.549,...,1938.725,2474.099,1957.847,650.783,650.785,815.364,256.359,3514.308,0,0
23,NaN,21_s1m1_cell 23,cell 23,612.197,2364.809,1918.977,3879.139,1171.104,775.834,947.102,...,2494.719,2002.213,1364.039,719.848,681.900,846.912,540.029,3925.137,1,0
24,NaN,21_s1m1_cell 24,cell 24,489.860,2491.575,786.660,3600.945,1135.870,759.555,941.939,...,2334.365,2743.138,1676.619,733.093,692.585,934.345,331.309,4264.530,0,0
25,NaN,21_s1m1_cell 25,cell 25,461.896,1721.506,400.184,2551.570,1086.322,771.211,1069.144,...,1791.994,2261.890,2494.067,587.509,629.791,858.607,257.553,3022.650,0,0
26,NaN,21_s1m1_cell 26,cell 26,460.951,2662.546,2981.929,2226.330,1098.226,705.358,963.354,...,2486.908,1708.645,1196.588,854.327,632.454,605.551,287.338,3497.954,1,0
27,NaN,21_s1m1_cell 27,cell 27,603.708,1391.091,558.979,2398.632,1220.163,1021.118,1116.839,...,1931.074,2293.803,3172.774,643.476,666.133,1137.854,764.926,3086.896,0,0
28,NaN,21_s1m1_cell 28,cell 28,536.017,1663.531,420.169,2648.065,1136.866,843.322,1069.777,...,1890.267,2053.819,2985.171,591.150,633.140,797.793,291.009,3178.609,0,0
29,NaN,21_s1m1_cell 29,cell 29,671.506,1585.933,671.252,2071.955,1185.785,1016.380,1028.672,...,1663.878,2103.568,3653.700,587.883,792.849,1307.527,1260.094,2682.272,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10642,NaN,23_s2m5_cell 433,cell 10642,1201.339,4722.237,3184.206,6137.447,1402.518,1217.316,1089.166,...,2621.276,2062.789,1710.454,3264.953,3304.934,7436.171,10176.603,2847.314,1,1
10643,NaN,23_s2m5_cell 434,cell 10643,1260.095,5912.302,8343.175,4792.235,1379.076,1207.867,1129.352,...,3012.206,2108.518,1600.168,3807.727,1563.530,1449.629,875.930,3514.203,1,1
10644,NaN,23_s2m5_cell 435,cell 10644,1217.185,2540.647,1357.126,6972.280,1390.750,1237.120,1095.214,...,3151.317,2342.365,1813.313,3722.622,1742.228,2067.963,1509.084,3592.601,0,1
10645,NaN,23_s2m5_cell 436,cell 10645,1083.193,2357.743,2399.365,6009.328,1400.202,1221.667,1044.532,...,3110.071,2171.284,1608.397,3543.472,1442.188,1228.995,654.367,3345.528,1,0
10646,NaN,23_s2m5_cell 437,cell 10646,1323.879,2923.155,667.883,5748.105,1376.806,1233.451,1126.975,...,2357.096,3361.950,1989.646,3334.407,3876.484,3185.356,1589.493,3225.010,0,1
10647,NaN,23_s2m5_cell 438,cell 10647,1646.771,2034.677,1666.071,4705.713,1465.760,1229.961,1022.846,...,2792.557,2360.413,1554.518,3676.683,1475.621,1392.139,845.019,2854.212,1,1
10648,NaN,23_s2m5_cell 439,cell 10648,1481.107,2231.922,2087.268,3631.609,1458.531,1231.914,1057.589,...,2704.325,2355.505,1660.125,3664.133,1534.135,1722.312,1143.401,2965.714,1,1
10649,NaN,23_s2m5_cell 440,cell 10649,1440.103,2607.849,881.101,6366.771,1401.418,1302.923,1422.272,...,2695.861,2487.495,2055.077,4051.820,2315.127,2933.464,1369.375,3594.214,0,1
10650,NaN,23_s2m5_cell 441,cell 10650,1334.827,3529.910,2669.528,7072.077,1454.482,1311.059,1313.192,...,4006.549,2620.184,1805.053,4787.081,1604.267,2634.393,685.302,4437.168,1,0
10651,NaN,23_s2m5_cell 442,cell 10651,1092.567,3134.998,574.529,5046.661,1368.676,1330.021,1132.722,...,1895.831,3752.556,2951.624,2679.791,1454.186,4165.684,2089.533,2585.713,0,1
10652,NaN,23_s2m5_cell 443,cell 10652,1173.750,3844.592,3434.863,6550.646,1421.182,1249.417,1037.092,...,3941.788,2696.532,1683.602,5009.043,1529.653,3160.161,1040.292,4394.798,1,1
10653,NaN,23_s2m5_cell 444,cell 10653,1109.007,5328.785,1503.246,6424.943,1402.650,1295.626,1018.774,...,3313.175,4847.993,2876.596,3945.515,1501.519,4068.906,1802.539,3712.067,1,1
10654,NaN,23_s2m5_cell 445,cell 10654,1080.829,3575.774,3488.376,7345.494,1400.377,1233.451,1017.047,...,3792.138,2457.819,1793.418,4882.805,1534.792,1952.348,940.648,4243.227,1,1
10655,NaN,23_s2m5_cell 446,cell 10655,1553.253,1564.450,574.220,381.066,1436.171,1238.645,1034.565,...,262.916,2184.517,27425.596,344.248,1645.729,3775.422,4630.975,427.271,0,1
10656,NaN,23_s2m5_cell 447,cell 10656,1122.101,1487.616,613.699,325.896,1523.664,1242.226,990.265,...,246.673,2253.012,1382.027,301.935,1269.580,2641.824,909.583,402.571,0,1
10657,NaN,23_s2m5_cell 448,cell 10657,1157.649,1532.372,717.120,320.292,1597.275,1243.318,1043.988,...,244.718,2350.346,1423.873,309.148,1351.746,2738.607,1016.833,404.440,0,1
10658,NaN,23_s2m5_cell 449,cell 10658,898.765,2124.038,819.428,4274.258,1386.656,1241.887,1083.648,...,2115.541,3098.526,1882.922,3356.868,1611.061,6164.033,3909.530,2940.685,0,1
10659,NaN,23_s2m5_cell 450,cell 10659,1374.692,1499.566,579.667,371.866,1370.884,1202.983,986.329,...,268.855,2039.588,33174.578,360.855,1475.627,2089.057,1794.778,547.486,0,1
10660,NaN,23_s2m5_cell 451,cell 10660,1082.643,1492.770,678.976,317.685,1658.703,1260.396,1048.441,...,250.973,2485.234,1471.086,313.633,1434.727,2431.143,1103.137,418.832,0,1
10661,NaN,23_s2m5_cell 452,cell 10661,1462.765,4109.420,1486.639,5034.137,1358.959,1221.978,1012.685,...,2907.172,2060.730,1769.366,3934.725,1758.632,2305.417,1625.500,3713.452,0,1
10662,NaN,23_s2m5_cell 453,cell 10662,807.476,3099.326,3638.127,4457.253,1349.074,1196.167,1006.035,...,3196.301,1887.198,1576.413,3961.844,1430.633,1421.537,783.334,3483.287,1,0
10663,NaN,23_s2m5_cell 454,cell 10663,988.037,1359.498,523.357,353.138,1288.703,1186.454,939.772,...,354.196,1722.756,20641.334,556.772,1440.829,1741.546,1284.671,823.134,0,1
10664,NaN,23_s2m5_cell 455,cell 10664,776.304,2289.537,2078.663,2347.032,1364.893,1194.288,986.767,...,1900.573,1913.638,1504.537,2963.010,1574.291,1888.032,1312.913,2589.851,1,1
10665,NaN,23_s2m5_cell 456,cell 10665,793.235,1287.015,535.832,344.674,1260.659,1178.958,929.225,...,276.074,1555.953,15318.738,355.696,1331.104,1236.212,738.146,494.726,0,0
10666,NaN,23_s2m5_cell 457,cell 10666,1142.176,2256.070,1639.552,5368.930,1363.650,1282.809,988.130,...,2373.184,2211.485,2025.508,3322.257,1879.032,3837.997,3356.274,3053.856,1,1
10667,NaN,23_s2m5_cell 458,cell 10667,1177.950,2689.598,2756.862,4436.351,1446.288,1257.858,1005.053,...,2898.238,2041.018,1641.001,3374.491,1626.323,2782.315,2203.175,3222.936,1,1
10668,NaN,23_s2m5_cell 459,cell 10668,1084.212,1520.146,709.164,315.369,1539.201,1283.480,1005.844,...,247.416,1902.658,1402.561,293.473,1317.444,2195.271,867.341,399.250,0,1
10669,NaN,23_s2m5_cell 460,cell 10669,1134.498,2531.540,1010.463,5662.223,1378.762,1303.295,1002.945,...,2585.735,2869.685,3069.165,3611.495,1598.963,5116.087,3133.865,3071.363,0,1
10670,NaN,23_s2m5_cell 461,cell 10670,1069.561,3109.789,3357.271,5675.363,1252.552,1083.666,887.379,...,4109.876,2672.130,1959.346,5253.586,1566.262,2438.544,743.254,4602.046,1,0
10671,NaN,23_s2m5_cell 462,cell 10671,1288.273,5983.552,1180.479,5656.707,1433.615,1283.000,1035.776,...,2912.233,5477.224,10313.843,3981.734,2348.213,6155.098,3884.273,3153.609,0,1

In [24]:
#drop non Pax, non Parv data
roi_df2 = roi_df[['binaryPax','binaryParv']]
roi_df2[0:10]

   binaryPax  binaryParv
0          0           0
1          0           0
2          0           0
3          0           0
4          0           0
5          0           0
6          0           0
7          0           0
8          0           1
9          0           1

In [35]:
print("Both binaryPax and binaryParv: " + str(len(roi_df2[(roi_df2['binaryPax'] == 1) & (roi_df2['binaryParv'] == 1)])))
print("Only binaryPax: " + str(len(roi_df2[(roi_df2['binaryPax'] == 1) & (roi_df2['binaryParv'] == 0)])))
print("Only binaryParv: " + str(len(roi_df2[(roi_df2['binaryPax'] == 0) & (roi_df2['binaryParv'] == 1)])))
print("Niether binaryPax nor binaryParv: " + str(len(roi_df2[(roi_df2['binaryPax'] == 0) & (roi_df2['binaryParv'] == 0)])))

Both binaryPax and binaryParv: 1274
Only binaryPax: 2592
Only binaryParv: 3301
Niether binaryPax nor binaryParv: 3505

In [12]:
# produce the clustergram using the dataframe that we created above
net.load_df(roi_df2)
# normalize our data
net.normalize(axis='column', norm_type='zscore', keep_orig=True)
#runs clustering with default parameters. LOOK INTO PARAMETERS - default is linkage type average
net.cluster()
net.widget()

clustergrammer_widget(network='{"row_nodes": [{"name": 0, "ini": 995, "clust": 846, "rank": 0, "rankvar": 0, "…

In [13]:
cluster1=net.widget_df()